name: portfolio_site
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2 # Typewriter animation package
  google_fonts: ^5.1.0
  line_icons: ^2.0.0
  url_launcher: ^6.1.7
  lottie: ^3.2.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2  # Launcher icon package for iOS and Android

flutter:
  assets:
    - assets/images/
    - assets/loading_animation.json
    
  uses-material-design: true

  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Regular.ttf
    - family: FiraCodeBold
      fonts:
        - asset: assets/fonts/FiraCode-Bold.ttf
          weight: 700
    - family: FiraCodeLight
      fonts:
        - asset: assets/fonts/FiraCode-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"  # Path to your app icon
